apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "35.2.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"

    ingressClass:
      enabled: true
      isDefaultClass: false
      name: external

    providers:
      kubernetesCRD:
        ingressClass: external
      kubernetesIngress:
        ingressClass: external

    gateway:
      enabled: false

    service:
      spec:
        loadBalancerIP: 34.78.144.3
