apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: demo-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "backstage-sales-eng@spotify.com"
    privateKeySecretRef:
      name: demo-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: external
