apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ${{ values.component_id }}
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${{ values.component_id }}
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${{ values.component_id }}
